### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Loko415** [Pr0t0ns/Discord-Token-Generator#9]
you can close this if its unrelated sorry. but how exactly do you make a generator make unlocked tokens? How does discord "patch" token generators?. Thats the part i dont understand so if you could explain to me i would greatly appreciate it since im planning to make my own private generator. Nice work by the way big fan

**Comment by Pr0t0ns** [comment]
Well it all depends, for unlocked tokens you need quite a few things, first you would need proxy support because discord can ratelimit you if they detect a lot of requests coming in from the same IP so proxy is a good way to change it and then you would need high quality proxies because free open proxies might have already been used for stuff like generating accounts so discord might already have them rate limited. Another thing to take into account with generating unlocked tokens is the captcha responses because discord is marking captcha responses from these big company's like anticaptcha, capmonster, 2captcha as potential spam so the tokens usually will get locked instantly, a way around this is adding a AI Captcha Solver (You can find a few open source ones that still work with the new versions of Hcaptcha and modify it to work with your generating by changing the motion data and etc.). And the patching is basically if discord changes there site key for captcha or makes an update to one of there API's to maybe require something new in the headers or payload (I believe discord is on V9 of their API's). Also a tip for your private generator, you should def add cookie stuffing for the session cookies just to make sure your making everything look legit.
